# Generated by Django 4.2.10 on 2024-04-13 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='final_aprove_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event', verbose_name='Event'),
        ),
    ]
