# Generated by Django 4.2.10 on 2024-04-21 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_requestmap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestmap',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request', verbose_name='Request'),
        ),
        migrations.AlterField(
            model_name='requestmap',
            name='sendto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.administrator', verbose_name='Administrator'),
        ),
    ]
